### PR TITLE
Upgrade to Spring Social 1.1.0 and Jackson 2

### PR DESCRIPTION
**Pull request by arakelian**

### CODE REVIEW

**Comment by kdekooter** [comment]
Any plans on performing this merge? Is this project still alive??

**Comment by a1u** [comment]
It seems it is dead repository...

**Comment by vbfischer** [comment]
Not entirely dead, I just don't have much time to work on it as I'm doing more Node.js than Java these days.

**Comment by kdekooter** [comment]
Thanks Bryce!

**Comment by vbfischer** [comment]
I can transfer ownership of the project if anyone wants to take it over

**Comment by anthonyikeda** [comment]
Tempting, I have some upcoming work using multiple storage providers. What are the criteria to take over the project?

**Comment by vbfischer** [comment]
Just be more active with it than I am. I don't have the time or enthusiasm to keep up with changes to either Spring and/or Dropbox API as I'm mostly working in the Node/JS world these days. Would prefer to transfer it to someone who is actively using it so that it would get the attention it deserves.

**Pull request merged**
